# Generated by Django 4.2 on 2023-04-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0002_remove_trait_pets'),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='traits',
            field=models.ManyToManyField(to='traits.trait'),
        ),
    ]
